default: &default
  adapter: postgresql
  encoding: unicode
  username: 'musa_jabbaaru'
  password: 'searock'
  pool: 5
  timeout: 5000
  host: 'localhost'
development:
  <<: *default
  database: 'work_orders'
test:
  <<: *default
  database: 'work_orders_test'
production:
  <<: *default
  database: 'work_orders'